steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - CloudFunction_For_CICD_Test
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
